version: "3.6"

services:
  account:
    build:
      context: "."
      dockerfile: "./account/app.dockerfile"
    depends_on:
      - "account_db"
    environment:
      DATABASE_URL: "postgres://spidey:123456@account_db/spidey?sslmode=disable"

  catalog:
    build:
      context: "."
      dockerfile: "./catalog/app.dockerfile"
    depends_on:
      - "catalog_db"
    environment:
      DATABASE_URL: "postgres://spidey:123456@catalog_db/spidey?sslmode=disable"

  order:
    build:
      context: "."
      dockerfile: "./order/app.dockerfile"
    depends_on:
      - "order_db"
    environment:
      DATABASE_URL: "postgres://spidey:123456@order_db/spidey?sslmode=disable"
      ACCOUNT_SERVICE_URL: "account:8080"
      CATALOG_SERVICE_URL: "catalog:8080"

  graphql:
    build:
      context: "."
      dockerfile: "./graphql/app.dockerfile"
    ports:
      - "8000:8080"
    depends_on:
      - "account"
      - "catalog"
    environment:
      ACCOUNT_SERVICE_URL: "account:8080"
      CATALOG_SERVICE_URL: "catalog:8080"
      ORDER_SERVICE_URL: "order:8080"

  account_db:
    build:
      context: "./account"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "spidey"
      POSTGRES_USER: "spidey"
      POSTGRES_PASSWORD: "123456"
    restart: "unless-stopped"

  catalog_db:
    build:
      context: "./catalog"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "spidey"
      POSTGRES_USER: "spidey"
      POSTGRES_PASSWORD: "123456"
    restart: "unless-stopped"

  order_db:
    build:
      context: "./order"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "spidey"
      POSTGRES_USER: "spidey"
      POSTGRES_PASSWORD: "123456"
    restart: "unless-stopped"
